### PR TITLE
add go mod

### PR DESCRIPTION
**Pull request by kayslay**
add go mod file after facing a bug in go v1.11

### CODE REVIEW

**Comment by rpip** [comment]
thanks @kayslay. Could you share more on the bug in go v1.11 that prompted this fix?

**Comment by kayslay** [comment]
when installing/updating the package returns 
`$ go get -u`
```
...
# github.com/rpip/paystack-go
../../../../pkg/mod/github.com/rpip/paystack-go@v0.0.0-20180509111153-5333b023a74e/bank.go:3:8: can't find import: "fmt"
```
since the package failed to install completely, when building it returns this error
```
../../../../pkg/mod/github.com/rpip/paystack-go@v0.0.0-20180509111153-5333b023a74e/plan_test.go:1:1: expected 'package', found 'EOF'
makefile:2: recipe for target 'run' failed
make: *** [run] Error 1
```

**Comment by rpip** [comment]
Understood. What's the difference between this PR #3 and the other opened PR #4?

Also, can you update the Travis script to ensure this module support build works? E.g:

```
script:
  - env GO111MODULE=on go build 
  - env GO111MODULE=on go test
```

**Comment by rpip** [comment]
hi @kayslay, please help here: what's the difference between this PR #3 and the other opened PR #4?

**Comment by kayslay** [comment]
I made a mistake in PR #3. I was trying to merge from my forked  master branch. PR #4 merges from the   `kayslay:rpip-module-name`

**Comment by rpip** [comment]
So this #4 PR is where the fix is? Will review.

Thanks

**Comment by rpip** [comment]
closing this #3 PR now.

**Comment by kayslay** [comment]
Yes

On Nov 9, 2018 16:16, "Yao Adzaku" <notifications@github.com> wrote:

So this #4 <https://github.com/rpip/paystack-go/pull/4> PR is where the fix
is? Will review.

Thanks

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/rpip/paystack-go/pull/3#issuecomment-437390318>, or mute
the thread

**Pull request closed without merging**
